# Generated by Django 3.2.5 on 2021-09-03 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(blank=True, max_length=100, unique=True)),
                ('nickname', models.CharField(blank=True, max_length=100, unique=True)),
                ('gender', models.CharField(default='', max_length=10)),
                ('created', models.DateField(auto_now_add=True)),
                ('match_gender', models.CharField(default='', max_length=10)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('introduce', models.CharField(default='', max_length=1000, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': ['user'],
                'verbose_name_plural': ['users'],
            },
        ),
    ]
