# Generated by Django 3.2.6 on 2021-08-23 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('gender', models.BooleanField()),
                ('introduce', models.TextField()),
                ('created', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '유저정보',
                'verbose_name_plural': '유저들 정보',
                'db_table': 'User',
                'ordering': ['created'],
            },
        ),
    ]
