# Generated by Django 3.2.6 on 2021-08-29 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_remove_account_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='gender',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='account',
            name='match_gender',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='account',
            name='username',
            field=models.CharField(default='', max_length=100, unique=True),
        ),
    ]
